import './globals.css'
import type { Metadata } from 'next'
import { Nunito_Sans } from 'next/font/google'

const nunitoSuns = Nunito_Sans({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Countries App',
  description: 'Generated by Alex Komanov',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={nunitoSuns.className}>{children}</body>
    </html>
  )
}
